// front-end/src/components/pages/E403.jsx
import React, {Component} from 'react';
import {NavLink} from 'react-router-dom';
import BC from '../BC';

class E403 extends Component {    
    render() {
        return (
            <div className="page-container center">
                <BC path={['Ошибка доступа']} />
                <h1>403</h1>
                <h2>Недостоточно прав для просмотра страницы</h2>
                <a onClick={this.props.history.goBack} className="btn">Назад</a>
                <NavLink to="/" className="btn btn-success">Главная</NavLink>
                <NavLink to="/auth/login" className="btn btn-info">Вход</NavLink>
            </div>
        );
    }
}

export default E403;

// front-end/src/views/E403.vue
<template>
    <div class="page-container center">
        <BC :path="['Ошибка доступа']" />
        <h1>403</h1>
        <h2>Недостоточно прав для просмотра страницы</h2>
        <a onclick="history.back()" class="btn">Назад</a>
        <router-link to="/" class="btn btn-success">Главная</router-link>
        <router-link to="/auth/login" class="btn btn-info">Вход</router-link>
    </div>
</template>
