// front-end/src/components/pages/E404.jsx
import React, {Component} from 'react';
import {NavLink} from 'react-router-dom';
import BC from '../BC';

class E404 extends Component {
    componentWillReceiveProps(nextProps) {
        console.log(nextProps);
    }
    
    render() {
        return (
            <div className="page-container center">
                <BC path={['Страница не найдена']} />
                <h1 className="pheader">404</h1>
                <h3 className="pheader">Страница не найдена</h3>
                <a onClick={this.props.history.goBack} className="button-default button-lg">Назад</a>
                <NavLink to="/" className="button-success button-lg">Главная</NavLink>
            </div>
        );
    }
}

export default E404;

// front-end/src/views/E404.vue
<template>
    <div class="page-container center">
        <BC :path="['Страница не найдена']" />
        <h1>404</h1>
        <h2>Страница не найдена</h2>
        <a onclick="history.back()" class="btn">Назад</a>
        <router-link to="/" class="btn btn-success">Главная</router-link>
    </div>
</template>
